swagger: "2.0"
info:
  title: Bird Watchers
  description: An API for Birds.
  contact:
    name: Birdwatchers United
  version: "0.0.1"
basePath: /birdwatchers
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
