openapi: 3.0.0
info:
  title: Bird Watchers
  description: An API for Birds.
  contact:
    name: Birdwatchers United
  version: 0.0.1
paths:
  /birds:
    get:
      summary: Get list of all birds in DB
      tags:
        - birds
      operationId: bird_watchers.handlers.birds.get_all
      responses:
        "200":
          description: Operation succeeded, array of all accounts
          content:
            application/json:
              schema:
                type: object
                properties:
                  birds:
                    description: List of all birds
                    type: array
                    items:
                      $ref: "#/components/schemas/Bird"
        default:
          description: Probably an error
  "/birds/{bird_name}":
    parameters:
      - $ref: "#/components/parameters/BirdName"
    get:
      summary: Get a specific bird
      tags:
        - birds
      operationId: bird_watchers.handlers.birds.get_one
      responses:
        "200":
          description: Operation succeeded, a bird
          content:
            application/json:
              schema:
                type: object
                properties:
                  bird:
                    $ref: "#/components/schemas/Bird"
        "401":
          description: Request is not authorized
        default:
          description: Probably an error
tags:
  - name: birds
    description: Avian endpoints
servers:
  - url: /birdwatchers
components:
  parameters:
    BirdName:
      name: bird_name
      description: Unique name associated with the bird
      in: path
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 128
  schemas:
    Bird:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 128
          description: Unique name associated with the bird
          example: Eurasian three-toed woodpecker
        wingspan:
          type: number
          example: 42
          description: How wide is the wingspan of this bird, in cm
        nest:
          $ref: "#/components/schemas/Nest"
    Nest:
      type: object
      description: Properties of the birds nest
      properties:
        type:
          type: string
          description: What kind of nest does the bird build
          enum:
            - platform
            - bowl
            - cavity
            - universal
        terrain:
          type: string
          description: Where does the bird nest
          enum:
            - swamp
            - plain
            - forest
            - universal
