openapi: 3.0.0
info:
  contact:
    name: Birdkeepers Assoc
  description: An API for registering kept birds.
  title: Bird Keepers
  version: 0.0.1
paths:
  /birds:
    post:
      operationId: bird_keepers.handlers.birds.register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OwnedBird"
      responses:
        "200":
          description: Operation succeeded, registered an owned bird
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OwnedBird"
        default:
          description: Probably an error
      summary: Create new owned bird
      tags:
        - accounts
tags:
  - description: Avian endpoints
    name: birds
servers:
  - url: /birdkeepers
components:
  parameters:
    BirdName:
      description: Unique name associated with the bird
      in: path
      name: bird_name
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 128
  schemas:
    Bird:
      properties:
        name:
          description: Unique name associated with the bird
          example: Eurasian three-toed woodpecker
          maxLength: 128
          minLength: 1
          type: string
        nest:
          $ref: "#/components/schemas/Nest"
        wingspan:
          description: How wide is the wingspan of this bird, in cm
          example: 42
          type: number
      type: object
    Nest:
      description: Properties of the birds nest
      properties:
        terrain:
          description: Where does the bird nest
          enum:
            - swamp
            - plain
            - forest
            - universal
          type: string
        type:
          description: What kind of nest does the bird build
          enum:
            - platform
            - bowl
            - cavity
            - universal
          type: string
      type: object
    OwnedBird:
      properties:
        bird:
          $ref: "#/components/schemas/Bird"
        owner_name:
          description: Who owns this bird
          example: Rasputin
          type: string
      type: object
